### ISSUE TITLE
str_replace(): Argument #3 ($subject) must be of type array|string, null given

### ISSUE THREAD

**Issue by hartenthaler** [huhwt/huhwt-wtlin#3]
> str_replace(): Argument #3 ($subject) must be of type array|string, null given …/modules_v4/huhwt-wtlin/LINaction.php:257
> #0 …/modules_v4/huhwt-wtlin/LINaction.php(257): str_replace()
> #1 …/app/Http/RequestHandlers/ModuleAction.php(85): HuHwt\WebtreesMods\LINchart\LINaction->getLINAction()
> #2 …/app/Http/Middleware/RequestHandler.php(54): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle()
> #3 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()

**Comment by hartenthaler** [comment]
This error never occurred again.
